# 断言操作（抛出异常）
## 举例1
```python

#!/usr/bin/env python
#-*- coding:utf8 -*-
'''
assert expression [,reason]
断言操作
'''

def division():
    '''
    功能:分苹果
    :return:
    '''
    print("\n ==========================分苹果了=================")
    apple = int(input('请输入苹果的个数：'))
    children = int(input("请输入小朋友的人数："))
    assert apple > children, '苹果不够分'
    result = apple//children
    remain = apple-result*children
    if remain>0:
        print("{}个苹果，平均分给{}个小朋友，每个人分{}个，剩下{}个".format(apple,children,result,remain))
    else:
        print("{}个苹果，平均分给{}个小朋友，每人分{}个".format(apple,children,result))

if __name__ == '__main__':
    try:
        division()      #调用分苹果函数
    except Exception as e:
        print("输入有误: ",e)

```

## 举例2
```python

#!/usr/bin/env python
#-*- coding:utf8 -*-
'''
assert <条件测试>.<异常附件数据>
'''

#assert语句时简化的raise语句，它引发异常的前提是其后面的条件测试为假
def testAssert():
    for i in range(3):
        try:
            assert i<2, "大于2了！！！"
        except AssertionError as e:
            print("Raise a AssertionError!",e)
        print(i)
    print('end......')

try:
    raise Exception('错误')
except Exception as e:
    print(e)

if __name__ == '__main__':
    testAssert()

```













































